# Generated by Django 5.1.4 on 2025-01-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_facility_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='district',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
