# Generated by Django 5.1.4 on 2025-01-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_facility_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
    ]
