# Generated by Django 5.1.4 on 2025-01-06 05:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_facility_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
